USE [master]
GO

/****** Object:  Database [PruebaC]    Script Date: 17/11/2021 19:05:25 ******/
CREATE DATABASE [PruebaC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PruebaC', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PruebaC.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PruebaC_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PruebaC_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PruebaC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PruebaC] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PruebaC] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PruebaC] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PruebaC] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PruebaC] SET ARITHABORT OFF 
GO

ALTER DATABASE [PruebaC] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PruebaC] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PruebaC] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PruebaC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PruebaC] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PruebaC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PruebaC] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PruebaC] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PruebaC] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PruebaC] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PruebaC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PruebaC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PruebaC] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PruebaC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PruebaC] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PruebaC] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PruebaC] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PruebaC] SET RECOVERY FULL 
GO

ALTER DATABASE [PruebaC] SET  MULTI_USER 
GO

ALTER DATABASE [PruebaC] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PruebaC] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PruebaC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PruebaC] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PruebaC] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PruebaC] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PruebaC] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PruebaC] SET  READ_WRITE 
GO

